@api = http://localhost:{{$dotenv PORT}}

### test enpoint
GET http://localhost:8080/healthz HTTP/1.1

### send mail
POST {{api}}/events HTTP/1.1
Content-Type: application/json
X-Hasura-From-Env: {{$dotenv API_SECRET}}

{
   "event": {
      "session_variables": {
            "x-hasura-role": "admin",
            "x-hasura-user-id": "ac118364-159a-4e27-bcad-ea1075595a79"
      },
      "op": "MANUAL",
      "data": {
            "old": null,
            "new": {
               "subject": "Test 97PX",
               "status": "pending",
               "createdAt": "2020-01-31T20:13:48.153043+00:00",
               "data": {
                  "intro": "Bonjour M. Xavier\nJe vous remercie pour votre prise de contact avec l'agence 97PX, je vois que vous avez tenté de déposer quelques clichés sur le serveur. Pour que nous puissions valider les photos, il faudrait déposer des fichiers HD ( nous ne proposons pas de fichier moyenne définition ), et bien insérer un titre pour la photo (la légende n'est pas indispensable). Par ailleurs, ce serait bien si vous pouviez remplir les informations de votre profil photographe. Si vous voulez échanger avec vous par téléphone pour mieux comprendre notre démarche, n'hésitez pas ( avec les limites du décalage horaire, nous sommes en Guyane)\nA bientôt\nPierre-Olivier Jay\n97PX\n05 94 31 57 97",
                  "name": "Xavier"
               },
               "to": "emmanuel.salomon@gmail.com",
               "userId": "c8269a12-1927-44fd-a226-07fdec95e34d",
               "id": "b7063074-a97e-45ba-98b8-ed7d853ba3ad"
            }
      }
   },
   "created_at": "2020-01-31T20:13:48.153043Z",
   "id": "67d7365f-97dc-463f-a3ee-6c290651f94f",
   "delivery_info": {
      "max_retries": 0,
      "current_retry": 0
   },
   "trigger": {
      "name": "send_mail"
   },
   "table": {
      "schema": "public",
      "name": "mail"
   }
}
